[tool.black]
  skip-string-normalization = true
  include = '''
  (
       \.pyi?$
     | \.py\.in$
  )
  '''
  exclude = '''
  (
       bindings/python/bt2/build/
     | bindings/python/bt2/setup\.py$
     | bindings/python/bt2/bt2/native_bt\.py$
     | bindings/python/bt2/bt2/__init__\.py$

  )
  '''
